# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dep-docker'
        repository: 'rkvarma4518/dep-docker'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          latest

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        # Folder that contains build artifacts (can be logs or any build output files)
        pathToPublish: '$(Build.ArtifactStagingDirectory)'  
        artifactName: 'dockerBuildLogs'
        publishLocation: 'Container'
