trigger:
- None

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ACR-Vars

stages:
# Stage 1: Pull Docker Image from Source ACR
- stage: PullImage
  jobs:
  - job: PullImageJob
    steps:
    # Step 1: Login to source ACR using username and password
    - script: |
        echo "$ACR_PASSWORD" | docker login $ACR_NAME.azurecr.io -u $ACR_USERNAME --password-stdin
      displayName: 'Login to Source ACR'
    
    # Step 2: Pull Docker Image
    - script: |
        docker pull $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
      displayName: 'Pull Docker Image'
    
    # Step 3: Tag the Docker Image
    - script: |
        docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:latest $DEST_ACR_NAME.azurecr.io/$DEST_IMAGE_NAME:v1
        docker images
      displayName: 'Tag Docker Image'

# Stage 2: Push Docker Image to Destination ACR
- stage: PushImage
  dependsOn: PullImage
  jobs:
  - job: PushImageJob
    steps:
    # Step 1: Login to destination ACR using service connection
    - task: Docker@2
      displayName: 'Login to Destination ACR'
      inputs:
        command: login
        containerRegistry: 'azure-registry-sc' # Name of the service connection

    # Step 2: Push Docker Image
    - script: |
        docker push $DEST_ACR_NAME.azurecr.io/$DEST_IMAGE_NAME:v1
      displayName: 'Push Docker Image'
